version: '3.8'
services:
  artsoft-postgres:
    container_name: artsoft-postgres-container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  smtp4dev:
    container_name: smtp4dev
    image: rnwood/smtp4dev
    ports:
      - "3000:80"
      - "2525:25"
    restart: always
    tty: true
    stdin_open: true
